---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "air-friends.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "air-friends.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
